### ISSUE TITLE
Is it still working?

### ISSUE THREAD

**Issue by AnthoPakPak** [15cm/Alfred-Workflow-JXA#1]
Hi!

I've just found this and thought it would be useful.
But I can't get it to work...

Do you know if it's still working on your side? Maybe it has been broken with newest MacOS versions…

Thanks 😉

**Comment by 15cm** [comment]
I don't use macOS anymore so can't help with that. BTW I'd recommend learning Swift/ObjC and write a simple CLI for this kind of purpose, if you cannot accomplish something by shell script or Apple script. JXA is too undocumented and limited to use LOL.
